// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearSSHHostKey removes the stored host key fingerprint for an SSH server.
 */
export function ClearSSHHostKey(host: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(185087189, host, port);
}

export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(301347162, id);
}

export function ListConnections(): $CancellablePromise<$models.Connection[] | null> {
    return $Call.ByID(645322174);
}

export function PickKeyFile(): $CancellablePromise<string> {
    return $Call.ByID(4201653029);
}

export function SaveConnection(c: $models.Connection): $CancellablePromise<$models.Connection> {
    return $Call.ByID(99910012, c);
}

/**
 * TestConnection verifies the full network path and returns the server version.
 */
export function TestConnection(c: $models.Connection): $CancellablePromise<$models.TestResult | null> {
    return $Call.ByID(854926829, c);
}
