// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowseOptions controls the table data browser.
 */
export interface BrowseOptions {
    "table": string;

    /**
     * empty = match all
     */
    "query": string;

    /**
     * 0-based
     */
    "page": number;
    "pageSize": number;
    "sortBy": string;
    "sortAsc": boolean;
}

/**
 * Connection describes a saved Manticore Search server connection.
 */
export interface Connection {
    "id": string;
    "name": string;

    /**
     * http | https
     */
    "scheme": string;
    "host": string;
    "port": number;

    /**
     * Manticore basic auth (optional)
     */
    "username": string;
    "password": string;

    /**
     * non-empty = cluster mode
     */
    "nodes"?: NodeAddress[] | null;

    /**
     * ordered network chain
     */
    "hops"?: Hop[] | null;

    /**
     * pre-chain configs, migrated on load
     */
    "net"?: legacyNet | null;
}

/**
 * Hop is one node of the network chain, applied left to right:
 * 本机 → hop1 → hop2 → … → Manticore. Any mix of proxy and SSH types is
 * allowed and the order is freely adjustable.
 */
export interface Hop {
    /**
     * http | socks5 | ssh
     */
    "type": string;
    "host": string;
    "port": number;
    "username"?: string;
    "password"?: string;
    "disabled"?: boolean;

    /**
     * SSH only
     * password | key
     */
    "authType"?: string;
    "keyPath"?: string;
    "keyPassphrase"?: string;

    /**
     * RemoteHost/RemotePort is where this hop tunnels to, as seen from the
     * hop itself. Empty = automatic (the next hop, or Manticore for the last).
     */
    "remoteHost"?: string;
    "remotePort"?: number;
}

/**
 * MutationResult reports a document write.
 */
export interface MutationResult {
    "message": string;
}

/**
 * NodeAddress is one Manticore node of a cluster connection.
 */
export interface NodeAddress {
    "scheme": string;
    "host": string;
    "port": number;
}

export interface ProxyHop {
    "type": string;
    "host": string;
    "port": number;
    "username"?: string;
    "password"?: string;
    "disabled"?: boolean;
}

/**
 * QueryResult is the normalized shape of any query, rendered by the data grid.
 */
export interface QueryResult {
    "columns": string[] | null;
    "rows": (any[] | null)[] | null;
    "total"?: number | null;
    "tookMs": number;
    "message"?: string;
    "error"?: string;
}

/**
 * TableInfo is one entry of the sidebar table list.
 */
export interface TableInfo {
    "name": string;
    "type": string;
    "docs"?: string;
}

/**
 * TestResult reports a successful connection test.
 */
export interface TestResult {
    "version": string;
    "via": string;
    "tookMs": number;
}

/**
 * legacyNet is the pre-chain network config; it is converted to Hops when a
 * saved connection is loaded.
 */
export interface legacyNet {
    "mode": string;
    "proxies"?: ProxyHop[] | null;
    "ssh"?: legacySSH | null;
}

export interface legacySSH {
    "host": string;
    "port": number;
    "username": string;
    "authType": string;
    "password": string;
    "keyPath": string;
    "keyPassphrase": string;
    "remoteHost": string;
    "remotePort": number;
}
