// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService executes raw SQL against a Manticore server and normalizes
 * every response shape into a QueryResult for the data grid.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExecuteSQL(connID: string, sql: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(490649504, connID, sql);
}
