// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TableService covers table inspection and document CRUD. Browsing uses the
 * Search API (DSL), writes use the Index API, schema uses SQL endpoints.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BrowseDocuments lists documents with pagination, optional full-text query
 * and sorting, through the Search API.
 */
export function BrowseDocuments(connID: string, opts: $models.BrowseOptions): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(3985249183, connID, opts);
}

/**
 * DeleteDocument removes a document by id.
 */
export function DeleteDocument(connID: string, table: string, id: string): $CancellablePromise<$models.MutationResult | null> {
    return $Call.ByID(2714811571, connID, table, id);
}

/**
 * DescribeTable returns the schema (DESCRIBE) of a table.
 */
export function DescribeTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(893819848, connID, table);
}

/**
 * DropTable deletes a table.
 */
export function DropTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(3260022628, connID, table);
}

/**
 * GetDocument fetches one document by id (numeric or string, e.g. percolate).
 */
export function GetDocument(connID: string, table: string, id: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(1968572814, connID, table, id);
}

/**
 * InsertDocument adds a document; id may be empty for auto-assignment.
 */
export function InsertDocument(connID: string, table: string, id: string, doc: { [_ in string]?: any } | null): $CancellablePromise<$models.MutationResult | null> {
    return $Call.ByID(171105093, connID, table, id, doc);
}

/**
 * ListTables returns the sidebar table list via SHOW TABLES.
 */
export function ListTables(connID: string): $CancellablePromise<$models.TableInfo[] | null> {
    return $Call.ByID(2908821588, connID);
}

/**
 * ReplaceDocument fully replaces a document.
 */
export function ReplaceDocument(connID: string, table: string, id: string, doc: { [_ in string]?: any } | null): $CancellablePromise<$models.MutationResult | null> {
    return $Call.ByID(275070722, connID, table, id, doc);
}

/**
 * ShowCreateTable returns the full CREATE statement of a table.
 */
export function ShowCreateTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(2809779176, connID, table);
}

/**
 * TruncateTable empties a table.
 */
export function TruncateTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(2213770053, connID, table);
}

/**
 * UpdateDocument updates the given (non full-text) fields of a document.
 */
export function UpdateDocument(connID: string, table: string, id: string, doc: { [_ in string]?: any } | null): $CancellablePromise<$models.MutationResult | null> {
    return $Call.ByID(2545080353, connID, table, id, doc);
}
