// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TableService covers table inspection, DDL, and document CRUD. Browsing uses
 * the Search API, writes use the Index API, schema changes use SQL.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplySchema runs ALTER statements in order and stops at the first error.
 * Statements before the failure are already applied.
 */
export function ApplySchema(connID: string, table: string, changes: $models.SchemaChange[] | null): $CancellablePromise<$models.SchemaApplyResult | null> {
    return $Call.ByID(1351127040, connID, table, changes);
}

/**
 * BrowseDocuments lists documents with pagination, optional full-text query
 * and sorting, through the Search API.
 */
export function BrowseDocuments(connID: string, opts: $models.BrowseOptions): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(3985249183, connID, opts);
}

/**
 * CreateTable executes a designer spec.
 */
export function CreateTable(connID: string, spec: $models.CreateTableSpec): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(160350419, connID, spec);
}

/**
 * CreateTableLike copies a table schema, optionally with data.
 */
export function CreateTableLike(connID: string, name: string, like: string, withData: boolean): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(1501946720, connID, name, like, withData);
}

/**
 * DeleteDocument removes a document by id.
 */
export function DeleteDocument(connID: string, table: string, id: string): $CancellablePromise<$models.MutationResult | null> {
    return $Call.ByID(2714811571, connID, table, id);
}

/**
 * DescribeTable returns the schema (DESCRIBE) of a table.
 */
export function DescribeTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(893819848, connID, table);
}

/**
 * DropTable deletes a table.
 */
export function DropTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(3260022628, connID, table);
}

/**
 * FlushRamchunk converts the RAM chunk into a new disk chunk.
 */
export function FlushRamchunk(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(3091570852, connID, table);
}

/**
 * FlushTable forces the RAM chunk to disk without rotating it.
 */
export function FlushTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(2301609131, connID, table);
}

/**
 * GetDocument fetches one document by id (numeric or string, e.g. percolate).
 */
export function GetDocument(connID: string, table: string, id: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(1968572814, connID, table, id);
}

/**
 * InsertDocument adds a document; id may be empty for auto-assignment.
 */
export function InsertDocument(connID: string, table: string, id: string, doc: { [_ in string]?: any } | null): $CancellablePromise<$models.MutationResult | null> {
    return $Call.ByID(171105093, connID, table, id, doc);
}

/**
 * ListTables returns the sidebar table list via SHOW TABLES.
 */
export function ListTables(connID: string): $CancellablePromise<$models.TableInfo[] | null> {
    return $Call.ByID(2908821588, connID);
}

/**
 * OptimizeTable merges disk chunks.
 */
export function OptimizeTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(518155174, connID, table);
}

/**
 * RenameTable renames a real-time table.
 */
export function RenameTable(connID: string, table: string, newName: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(3769294969, connID, table, newName);
}

/**
 * RenderCreateTable returns the CREATE statement for a designer spec.
 */
export function RenderCreateTable(spec: $models.CreateTableSpec): $CancellablePromise<$models.SQLPreview | null> {
    return $Call.ByID(936174203, spec);
}

/**
 * RenderSchemaChanges returns the ALTER statements for a design session.
 */
export function RenderSchemaChanges(table: string, changes: $models.SchemaChange[] | null): $CancellablePromise<$models.SQLPreview | null> {
    return $Call.ByID(463958479, table, changes);
}

/**
 * ReplaceDocument fully replaces a document.
 */
export function ReplaceDocument(connID: string, table: string, id: string, doc: { [_ in string]?: any } | null): $CancellablePromise<$models.MutationResult | null> {
    return $Call.ByID(275070722, connID, table, id, doc);
}

/**
 * ShowCreateTable returns the full CREATE statement of a table.
 */
export function ShowCreateTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(2809779176, connID, table);
}

/**
 * ShowTableSettings returns SHOW TABLE … SETTINGS.
 */
export function ShowTableSettings(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(3416343961, connID, table);
}

/**
 * ShowTableStatus returns SHOW TABLE … STATUS.
 */
export function ShowTableStatus(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(57750910, connID, table);
}

/**
 * TruncateTable empties a table.
 */
export function TruncateTable(connID: string, table: string): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(2213770053, connID, table);
}

/**
 * UpdateDocument updates the given (non full-text) fields of a document.
 */
export function UpdateDocument(connID: string, table: string, id: string, doc: { [_ in string]?: any } | null): $CancellablePromise<$models.MutationResult | null> {
    return $Call.ByID(2545080353, connID, table, id, doc);
}
